<?php $categories = $this->getFeaturedCategoryCollection(); ?>

<h3 class="title">Featured Categories</h3>
<div class="home-page-category-box">
  <?php foreach($categories as $category): ?>
      <div class="item">
          <a href="<?php echo $category->getUrl(); ?>">
            <img class="category-image" src="<?php echo $category->getImageUrl()?>" alt="<?php echo $category->getName(); ?>">
          </a>
          <span class="caption"><?php echo $category->getName(); ?></span>
      </div>
  <?php endforeach; ?>
</div>

</br>
